# Generated by Django 5.2.17 on 2026-08-10 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_venue'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Optional: which Organization (tenant) this event belongs to. Nullable and additive — existing events with no organization are unaffected. See organizations.models.Organization for the scope of what this field does and does not enforce.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='organizations.organization'),
        ),
    ]
