# Generated by Django 5.2.17 on 2026-08-09 17:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 code, e.g. USD, EUR, INR.', max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
                ('rate_to_base', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='How many units of this currency equal 1 unit of the base currency (INR).', max_digits=12)),
                ('is_base', models.BooleanField(default=False, help_text="Exactly one currency should be marked base — this project's base is INR.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
    ]
