# Generated by Django 5.2.17 on 2026-08-09 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('certificate', 'Certificate'), ('badge', 'Digital Badge')], default='certificate', max_length=15)),
                ('title', models.CharField(default='Certificate of Attendance', help_text="Shown on the PDF, e.g. 'Certificate of Attendance', 'Volunteer Badge'.", max_length=150)),
                ('badge_level', models.CharField(blank=True, choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=10)),
                ('certificate_code', models.CharField(editable=False, max_length=24, unique=True)),
                ('verify_token', models.TextField(blank=True, editable=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('revoked', models.BooleanField(default=False, help_text='A revoked certificate still exists (audit trail) but fails public verification.')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
