# Generated by Django 5.2.17 on 2026-08-10 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='EventSphere', max_length=100)),
                ('support_email', models.EmailField(default='support@example.com', max_length=254)),
                ('allow_new_signups', models.BooleanField(default=True, help_text='If off, the signup page still loads but rejects new account creation.')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='If on, everyone except Super Admins sees a maintenance page for the whole site.')),
                ('maintenance_message', models.TextField(blank=True, default="We're performing scheduled maintenance. Please check back shortly.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'platform settings',
            },
        ),
    ]
