# Generated by Django 5.2.17 on 2026-08-07 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_event_venue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('ticket_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('vip', 'VIP')], default='free', max_length=10)),
                ('qr_token', models.TextField(blank=True, editable=False, help_text='Signed payload (django.core.signing) encoded into the QR image. Verifying it re-checks the signature, so a forged/edited token is rejected.')),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('checked_in', 'Checked In'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='issued', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_checked_in', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_checked_out', to=settings.AUTH_USER_MODEL)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='events.registration')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckInLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('duplicate_rejected', 'Duplicate Scan Rejected'), ('invalid', 'Invalid')], max_length=20)),
                ('detail', models.CharField(blank=True, help_text="Human-readable context, e.g. 'Already checked in at 6:04 PM by J. Rao'.", max_length=255)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_logs', to='events.event')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_scans', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, help_text="Blank when the scanned token didn't resolve to any ticket at all.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkin_logs', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
